# Generated by Django 5.1.1 on 2024-09-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Egressos',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('tel', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=80)),
                ('curso', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('FIN', 'Finalizado'), ('INT', 'Interrompido')], max_length=20)),
                ('profissao_atual', models.CharField(max_length=50)),
                ('empresa_atual', models.CharField(max_length=50)),
                ('deseja_parcerias', models.BooleanField(default=False)),
                ('deseja_partEvent', models.BooleanField(default=False)),
                ('deseja_fazerNewCursos', models.BooleanField(default=False)),
            ],
        ),
    ]
